CREATE DATABASE foodmap;
USE foodmap;

CREATE TABLE IF NOT EXISTS usuario(
EMAIL VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
SENHA VARCHAR(40) NOT NULL,
ADM BOOLEAN
);

CREATE TABLE IF NOT EXISTS restaurante(
COD_RESTAURANTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(30) NOT NULL,
CATEGORIA VARCHAR(30) NOT NULL,
ENDERECO VARCHAR(30) NOT NULL,
IMAGEM VARCHAR(40) NOT NULL

);

SELECT * FROM RESTAURANTE